### ISSUE TITLE
storage_volume and storage_space_left only apply to High and HighHVA

### ISSUE THREAD

**Issue by ejaronne** [CMSgov/cms-ars-5.0-red-hat-enterprise-linux-8-stig-overlay#4]
https://github.com/CMSgov/cms-ars-5.0-red-hat-enterprise-linux-8-stig-overlay/blob/9fa991c57648bc260e266253ec5c41dfc89b5540/inspec.yml#L285-L296 

They should not over-ride the baseline (just leave alone) for other baselines.

**Comment by ssayed118** [comment]
Issues fixed with commit e60fadf81ea86cc8d18e8b2279a19925e3024b74
