### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by karikarshivani** [CMSgov/cms-ars-5.0-red-hat-enterprise-linux-8-stig-overlay#5]
- [x] Non-ARS check: Use the NA Caveats worksheet (column I) to check if any RHEL 8 controls are not in ARS.
- [x] Remove sys_cat verbiage: In the for loop, change the caveat to `"Not applicable for this CMS ARS 5.0 overlay, since the requirement is not included in CMS ARS 5.0"`

**Comment by ssayed118** [comment]
This issue was fixed with the dfec301c537843f8d541019e79d49eb80ad0a7d0 commit.
